export const projects = [
  {
    title: 'Password Generator',
    description: "Create an application that an employee can use to generate a random password based on criteria. This app will run in the browser, and feature dynamically updated HTML and CSS powered by JavaScript. It will have a clean and polished user interface that is responsive, ensuring that it adapts to multiple screen sizes.",
    image: './images/password-generator.png',
    tags: ['HTML', 'Javascript', 'CSS'],
    visit: 'https://github.com/AMDWorkspace/password-generator',
    source: 'https://amdworkspace.github.io/password-generator/',
    id: 3,
  },
  {
    title: 'Find an Author',
    description:'An application that allows users / students to search different categories of books, authors, and their list of titles using HTML, CSS, JS, and third-party APIs. The appplication will also provide features such as if the book is available for purchase, for rent / borrow, or free to download for all users. The user may also narrow down their search by year of publishing, high reviews, previews of each book, and bibliographic information.',
    image: '/images/find-an-author.jpg',
    tags: ['API', 'JavaScript'],
    visit: 'https://github.com/polizoto/find-an-author',
    source: 'https://polizoto.github.io/find-an-author/',
    id: 1,
  },
  {
    title: 'Weather Dashboard',
    description: "A weather dashboard that will run in the browser and feature dynamically updated HTML, CSS, Javascript, BootStrap, Moment.js, and the OpenWeather API to retrieve weather data for cities.",
      image: './images/weather-dashboard.jpg',
      tags: ['API', 'Javascript'],
    visit: 'https://github.com/AMDWorkspace/weather-dashboard-challenge',
    source: 'https://amdworkspace.github.io/weather-dashboard-challenge/',
    id: 2,
  },
  {
    title: 'Dream Journal',
    description: "This application assists a user in recording their dreams",
      image: "./images/dream-journal.jpg",
      tags: ['Mongo', 'Express', 'Node'],
    visit: 'https://github.com/reinholz36/Dream-Journal',
    source: 'https://frozen-atoll-87689.herokuapp.com/',
    id: 0,
  },
];